# Generated by Django 4.2 on 2025-05-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='prefix',
            field=models.CharField(default='RP', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
