# Generated by Django 4.2 on 2025-06-28 03:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='thirty_days_task',
            new_name='parent_task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='seven_days',
            new_name='sprint',
        ),
        migrations.RenameField(
            model_name='thirtydaystask',
            old_name='thirty_days',
            new_name='sprint',
        ),
        migrations.AlterField(
            model_name='task',
            name='risk_impact',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='risk_likelihood',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='task',
            name='unattained_reason',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='thirtydaystask',
            name='risk_impact',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='thirtydaystask',
            name='risk_likelihood',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='thirtydaystask',
            name='unattained_reason',
            field=models.TextField(default='', null=True),
        ),
    ]
