# Generated by Django 4.2 on 2025-05-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epic',
            name='issue_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='subtask',
            name='issue_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='issue_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='epic',
            name='risk_level',
            field=models.CharField(choices=[('L', 'Low'), ('MI', 'Medium-I'), ('MII', 'Medium-II'), ('H', 'High'), ('C', 'Critical')], default='L', max_length=10),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='risk_level',
            field=models.CharField(choices=[('L', 'Low'), ('MI', 'Medium-I'), ('MII', 'Medium-II'), ('H', 'High'), ('C', 'Critical')], default='L', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='risk_level',
            field=models.CharField(choices=[('L', 'Low'), ('MI', 'Medium-I'), ('MII', 'Medium-II'), ('H', 'High'), ('C', 'Critical')], default='L', max_length=10),
        ),
    ]
