# Generated by Django 4.2 on 2025-05-25 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_activityhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityhistory',
            name='epic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.epic'),
        ),
        migrations.AlterField(
            model_name='activityhistory',
            name='subtask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.subtask'),
        ),
        migrations.AlterField(
            model_name='activityhistory',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tasks.task'),
        ),
    ]
